config/routes.rb
Ruby2Rails4::Application.routes.draw do
  resources :shains

  

end

app/models/shain.rb
class Shain < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shains_controller.rb
class ShainsController < ApplicationController
  before_action :set_shain, only: [:show, :edit, :update, :destroy]

  # GET /shains
  # GET /shains.json
  def index
    @shains = Shain.all
  end

  # GET /shains/1
  # GET /shains/1.json
  def show
  end

  # GET /shains/new
  def new
    @shain = Shain.new
  end

  # GET /shains/1/edit
  def edit
  end

  # POST /shains
  # POST /shains.json
  def create
    @shain = Shain.new(shain_params)

    respond_to do |format|
      if @shain.save
        format.html { redirect_to @shain, notice: 'Shain was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shain }
      else
        format.html { render action: 'new' }
        format.json { render json: @shain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shains/1
  # PATCH/PUT /shains/1.json
  def update
    respond_to do |format|
      if @shain.update(shain_params)
        format.html { redirect_to @shain, notice: 'Shain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shains/1
  # DELETE /shains/1.json
  def destroy
    @shain.destroy
    respond_to do |format|
      format.html { redirect_to shains_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shain
      @shain = Shain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shain_params
      params.require(:shain).permit(:shainName, :shainNameYomi, :tel1, :tel2, :postNo, :address1, :address2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shains_helper.rb
module ShainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby2Rails4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shains/_form.html.erb
<%= form_for(@shain) do |f| %>
  <% if @shain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shain.errors.count, "error") %> prohibited this shain from being saved:</h2>

      <ul>
      <% @shain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shainName %><br>
    <%= f.text_field :shainName %>
  </div>
  <div class="field">
    <%= f.label :shainNameYomi %><br>
    <%= f.text_field :shainNameYomi %>
  </div>
  <div class="field">
    <%= f.label :tel1 %><br>
    <%= f.text_field :tel1 %>
  </div>
  <div class="field">
    <%= f.label :tel2 %><br>
    <%= f.text_field :tel2 %>
  </div>
  <div class="field">
    <%= f.label :postNo %><br>
    <%= f.text_field :postNo %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shains/edit.html.erb
<h1>Editing shain</h1>

<%= render 'form' %>

<%= link_to 'Show', @shain %> |
<%= link_to 'Back', shains_path %>

app/views/shains/index.html.erb
<h1>Listing shains</h1>

<table>
  <thead>
    <tr>
      <th>Shainname</th>
      <th>Shainnameyomi</th>
      <th>Tel1</th>
      <th>Tel2</th>
      <th>Postno</th>
      <th>Address1</th>
      <th>Address2</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shains.each do |shain| %>
      <tr>
        <td><%= shain.shainName %></td>
        <td><%= shain.shainNameYomi %></td>
        <td><%= shain.tel1 %></td>
        <td><%= shain.tel2 %></td>
        <td><%= shain.postNo %></td>
        <td><%= shain.address1 %></td>
        <td><%= shain.address2 %></td>
        <td><%= link_to 'Show', shain %></td>
        <td><%= link_to 'Edit', edit_shain_path(shain) %></td>
        <td><%= link_to 'Destroy', shain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shain', new_shain_path %>

app/views/shains/new.html.erb
<h1>New shain</h1>

<%= render 'form' %>

<%= link_to 'Back', shains_path %>

app/views/shains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shainname:</strong>
  <%= @shain.shainName %>
</p>

<p>
  <strong>Shainnameyomi:</strong>
  <%= @shain.shainNameYomi %>
</p>

<p>
  <strong>Tel1:</strong>
  <%= @shain.tel1 %>
</p>

<p>
  <strong>Tel2:</strong>
  <%= @shain.tel2 %>
</p>

<p>
  <strong>Postno:</strong>
  <%= @shain.postNo %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @shain.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @shain.address2 %>
</p>

<%= link_to 'Edit', edit_shain_path(@shain) %> |
<%= link_to 'Back', shains_path %>